name: Run Fooocus Script with Disk and Memory Allocation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-fooocus:
    runs-on: self-hosted  # Ensure this runner has GPU, sufficient disk, and memory resources.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Allocate Disk Space
      run: |
        mkdir -p /tmp/fooocus_disk
        df -h /tmp  # Check disk space availability for debugging

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygit2==1.15.1 packaging

    - name: Clone Fooocus Repository
      run: git clone https://github.com/lllyasviel/Fooocus.git /tmp/Fooocus

    - name: Install Fooocus Dependencies
      run: |
        cd /tmp/Fooocus
        python -m pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Monitor Memory and Disk
      run: |
        free -h  # Check memory usage
        df -h    # Check disk usage

    - name: Run Fooocus Script
      run: |
        cd /tmp/Fooocus
        python entry_with_update.py --share --always-high-vram
