name: Fooocus with GPU

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-fooocus:
    runs-on: self-hosted  # Use your self-hosted runner with GPU

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygit2==1.15.1 packaging torch torchvision

    - name: Clone Fooocus Repository
      run: git clone https://github.com/lllyasviel/Fooocus.git /tmp/Fooocus

    - name: Install Fooocus Requirements
      run: |
        cd /tmp/Fooocus
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Fooocus Script
      run: |
        cd /tmp/Fooocus
        python entry_with_update.py --share --always-high-vram
